server:
  port: 8001

project:
  version: v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petlog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    redis:
      password: YOUR_PASSWORD
      timeout: 600ms
cloud:
  aws:
    s3:
      bucket: BUCKETNAME
    credentials:
      access-key: ACCESSKEY_STRING
      secret-key: SECRETKEY_STRING
    region:
      static: REGIONNAME
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: ERROR
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        secret-key: vwzd6rhhPVr2D3NYWiBMpiB3DX9JbaerzjPBUfN6IhuDa7AEzxZ5ojjZn6ugBNKJ
        expiration: 604800000