server:
  port: 8001

project:
  version: v1
storage:
  uri: ENC("n6I7hj2lozaEpcvpsJ4p6jkPT1l/he9ITISbaZRKcQZ9pTylwfc5O1q+jY7Gkx/G9k3TWahamxDqk+3UO0b1gw==")

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC("Mv2+qpTLspS24HBCacK6TSrmSOpV8VZceaevMgBAygnFInRFlknva1FWspnDpOWGK2n2VVcbjYlARmwo0M94IJ33BfT57cK1sncYmD/y0zRdQZG6T3ZhQPsnz1Egfb7vNYoDyW+I0fqxyQrw9gGfIxRN2lmjbgWjmhiWH96Wq9p8iC6j9pvjXUUjvGcNgBlqeutqt5kg+lQPr2o7a2Yrh8NxE2gpq2p35ol/z3xEeuQ=")
    username: ENC("uT5Scmzjid/mQarp8Wejpw==")
    password: ENC("sR4oLGgaxiuRiiOaI2C7An8iyrp6csnM")
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      password: ENC("m9TfKIXK76S38gkq/ZEWVh1x1uCGakwC")
      timeout: 600ms
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: ENC("9Yc3NWxdqvHrV+RT5ngZMYX06+835CeVRiNZRPKcwwE=")
cloud:
  aws:
    s3:
      bucket: ENC("DFq5C1E7ikVMVvEIAocccgRQALrs0lDK")
    credentials:
      access-key: ENC("+RB2HYst5ZTFuVsESnhgCaUKHaAY+JFQIrUQnxmTZt4=")
      secret-key: ENC("Ci5RcZkKwP6rjLy1JrXfbzBUCh3sIWAEwPG4YnXGI1ivU0M1dZy+JLkVI7vsqSDrdxtXapdoCS0=")
    region:
      static: ENC("J+EuG/dqH+tZRQWsHMVQLTEplBxbZX6z")
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: ERROR
application:
  security:
    jwt:
      secret-key: ENC("hXAEbSPJT5gr5QcjKJcmm+Hs6CUZaPaTSE8VEUsj+aWLkWXKyomk3nuWX0kZfW99H4sBcFn1BNN0PtBpMppT2vFhnK4vgEYSJPP8qGD9JdA=")
      expiration: 86400000
      refresh-token:
        secret-key: ENC("TIBlzwCvpD3HNPv9V/sjJDGni3t2SGk30Hmr5oIY/T3yeyr1dMGHraDLL2vzuFDwNOhYfk96QniY+nmbEIb6397c1PHa70XK1t2/mlOt9As=")
        expiration: 604800000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 10000
ffmpeg:
  path: /usr/bin