server:
  port: 8001

project:
  version: v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petlog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    redis:
      password: YOUR_PASSWORD
      timeout: 600ms
cloud:
  aws:
    s3:
      bucket: BUCKETNAME
    credentials:
      access-key: ACCESSKEY_STRING
      secret-key: SECRETKEY_STRING
    region:
      static: REGIONNAME
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: ERROR
application:
  security:
    jwt:
      secret-key: ENC("hXAEbSPJT5gr5QcjKJcmm+Hs6CUZaPaTSE8VEUsj+aWLkWXKyomk3nuWX0kZfW99H4sBcFn1BNN0PtBpMppT2vFhnK4vgEYSJPP8qGD9JdA=")
      expiration: 86400000
      refresh-token:
        secret-key: ENC("TIBlzwCvpD3HNPv9V/sjJDGni3t2SGk30Hmr5oIY/T3yeyr1dMGHraDLL2vzuFDwNOhYfk96QniY+nmbEIb6397c1PHa70XK1t2/mlOt9As=")
        expiration: 604800000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 10000